name = "HallThruster"
uuid = "2311f341-5e6d-4941-9e3e-3ce0ae0d9ed6"
authors = ["Thomas Marks <marksta@umich.edu>"]
version = "0.18.3"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[weakdeps]
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"

[extensions]
UnitfulExt = "Unitful"
DynamicQuantitiesExt = "DynamicQuantities"

[compat]
DelimitedFiles = "1"
DocStringExtensions = "0.9"
Documenter = "1"
DynamicQuantities = "1"
JSON3 = "1"
LinearAlgebra = "<0.0.1, 1"
Measures = "0.3"
OrderedCollections = "1"
PrecompileTools = "1"
Printf = "<0.0.1, 1"
RecipesBase = "1"
Statistics = "1"
Unitful = "1"
julia = "1.10"

[extras]
CPUSummary = "2a0fbf3d-bb9c-48f3-b0a9-814d99fd7ab9"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Symbolics", "Printf", "Statistics", "Unitful"]
