name = "HallThruster"
uuid = "2311f341-5e6d-4941-9e3e-3ce0ae0d9ed6"
authors = ["Thomas Marks <marksta@umich.edu>"]
version = "0.19.0"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[extensions]
DynamicQuantitiesExt = "DynamicQuantities"
UnitfulExt = "Unitful"

[compat]
Accessors = "0.1.42"
CairoMakie = "0.15.1"
DelimitedFiles = "1"
DocStringExtensions = "0.9"
Documenter = "1"
DocumenterCitations = "1.4.0"
DynamicQuantities = "1"
JSON3 = "1"
Libdl = "1"
LinearAlgebra = "<0.0.1, 1"
OrderedCollections = "1"
PrecompileTools = "1"
Printf = "<0.0.1, 1"
SafeTestsets = "0.1.0"
Statistics = "1"
TOML = "1.0.3"
Unitful = "1"
julia = "1.10"

[extras]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["Test", "Accessors", "Symbolics", "Printf", "Statistics", "SafeTestsets", "LinearAlgebra", "CairoMakie", "Documenter", "DocumenterCitations", "Unitful", "Libdl"]
